export const ROBSTRIDE_PARAM_CATALOG = [
  { id: 0x0000, name: 'Name', dataType: 'String', access: 'rw' },
  { id: 0x0001, name: 'BarCode', dataType: 'String', access: 'rw' },
  { id: 0x1000, name: 'BootCodeVersion', dataType: 'String', access: 'ro' },
  { id: 0x1001, name: 'BootBuildDate', dataType: 'String', access: 'ro' },
  { id: 0x1002, name: 'BootBuildTime', dataType: 'String', access: 'ro' },
  { id: 0x1003, name: 'AppCodeVersion', dataType: 'String', access: 'ro' },
  { id: 0x1004, name: 'AppGitVersion', dataType: 'String', access: 'ro' },
  { id: 0x1005, name: 'AppBuildDate', dataType: 'String', access: 'ro' },
  { id: 0x1006, name: 'AppBuildTime', dataType: 'String', access: 'ro' },
  { id: 0x1007, name: 'AppCodeName', dataType: 'String', access: 'ro' },
  { id: 0x2000, name: 'echoPara1', dataType: 'uint16', access: 'config' },
  { id: 0x2001, name: 'echoPara2', dataType: 'uint16', access: 'config' },
  { id: 0x2002, name: 'echoPara3', dataType: 'uint16', access: 'config' },
  { id: 0x2003, name: 'echoPara4', dataType: 'uint16', access: 'config' },
  { id: 0x2004, name: 'echoFreHz', dataType: 'uint32', access: 'rw' },
  { id: 0x2005, name: 'MechOffset', dataType: 'float', access: 'setting' },
  { id: 0x2006, name: 'MechPos_init', dataType: 'float', access: 'rw' },
  { id: 0x2007, name: 'limit_torque', dataType: 'float', access: 'rw' },
  { id: 0x2008, name: 'I_FW_MAX', dataType: 'float', access: 'rw' },
  { id: 0x2009, name: 'motor_baud', dataType: 'uint8', access: 'rw' },
  { id: 0x200a, name: 'CAN_ID', dataType: 'uint8', access: 'rw' },
  { id: 0x200b, name: 'CAN_MASTER', dataType: 'uint8', access: 'setting' },
  { id: 0x200c, name: 'CAN_TIMEOUT', dataType: 'uint32', access: 'rw' },
  { id: 0x200d, name: 'status2', dataType: 'int16', access: 'rw' },
  { id: 0x200e, name: 'status3', dataType: 'uint32', access: 'rw' },
  { id: 0x200f, name: 'status1', dataType: 'float', access: 'rw' },
  { id: 0x2010, name: 'status6', dataType: 'uint8', access: 'rw' },
  { id: 0x2011, name: 'cur_filt_gain', dataType: 'float', access: 'rw' },
  { id: 0x2012, name: 'cur_kp', dataType: 'float', access: 'rw' },
  { id: 0x2013, name: 'cur_ki', dataType: 'float', access: 'rw' },
  { id: 0x2014, name: 'spd_kp', dataType: 'float', access: 'rw' },
  { id: 0x2015, name: 'spd_ki', dataType: 'float', access: 'rw' },
  { id: 0x2016, name: 'loc_kp', dataType: 'float', access: 'rw' },
  { id: 0x2017, name: 'spd_filt_gain', dataType: 'float', access: 'rw' },
  { id: 0x2018, name: 'limit_spd', dataType: 'float', access: 'rw' },
  { id: 0x2019, name: 'limit_cur', dataType: 'float', access: 'rw' },
  { id: 0x201a, name: 'loc_ref_filt_gai', dataType: 'float', access: 'rw' },
  { id: 0x201b, name: 'limit_loc', dataType: 'float', access: 'rw' },
  { id: 0x201c, name: 'position_offset', dataType: 'float', access: 'rw' },
  { id: 0x201d, name: 'chasu_angle_offs', dataType: 'float', access: 'rw' },
  { id: 0x201e, name: 'spd_step_value', dataType: 'float', access: 'rw' },
  { id: 0x201f, name: 'vol_max', dataType: 'float', access: 'rw' },
  { id: 0x2020, name: 'acc_set', dataType: 'float', access: 'rw' },
  { id: 0x3000, name: 'timeUse0', dataType: 'uint16', access: 'ro' },
  { id: 0x3001, name: 'timeUse1', dataType: 'uint16', access: 'ro' },
  { id: 0x3002, name: 'timeUse2', dataType: 'uint16', access: 'ro' },
  { id: 0x3003, name: 'timeUse3', dataType: 'uint16', access: 'ro' },
  { id: 0x3004, name: 'encoderRaw', dataType: 'int16', access: 'ro' },
  { id: 0x3005, name: 'mcuTemp', dataType: 'int16', access: 'ro' },
  { id: 0x3006, name: 'motorTemp', dataType: 'int16', access: 'ro' },
  { id: 0x3007, name: 'vBus(mv)', dataType: 'uint16', access: 'ro' },
  { id: 0x3008, name: 'adc1Offset', dataType: 'int32', access: 'ro' },
  { id: 0x3009, name: 'adc2Offset', dataType: 'int32', access: 'ro' },
  { id: 0x300a, name: 'adc1Raw', dataType: 'uint16', access: 'ro' },
  { id: 0x300b, name: 'adc2Raw', dataType: 'uint16', access: 'ro' },
  { id: 0x300c, name: 'VBUS', dataType: 'float', access: 'ro' },
  { id: 0x300d, name: 'cmdId', dataType: 'float', access: 'ro' },
  { id: 0x300e, name: 'cmdIq', dataType: 'float', access: 'ro' },
  { id: 0x300f, name: 'cmdIocref', dataType: 'float', access: 'ro' },
  { id: 0x3010, name: 'cmdspdref', dataType: 'float', access: 'ro' },
  { id: 0x3011, name: 'cmdTorque', dataType: 'float', access: 'ro' },
  { id: 0x3012, name: 'cmdPos', dataType: 'float', access: 'ro' },
  { id: 0x3013, name: 'cmdVel', dataType: 'float', access: 'ro' },
  { id: 0x3014, name: 'rotation', dataType: 'int16', access: 'ro' },
  { id: 0x3015, name: 'modPos', dataType: 'float', access: 'ro' },
  { id: 0x3016, name: 'mechPos', dataType: 'float', access: 'ro' },
  { id: 0x3017, name: 'mechVel', dataType: 'float', access: 'ro' },
  { id: 0x3018, name: 'elecPos', dataType: 'float', access: 'ro' },
  { id: 0x3019, name: 'ia', dataType: 'float', access: 'ro' },
  { id: 0x301a, name: 'ib', dataType: 'float', access: 'ro' },
  { id: 0x301b, name: 'ic', dataType: 'float', access: 'ro' },
  { id: 0x301c, name: 'timeout', dataType: 'int32', access: 'ro' },
  { id: 0x301d, name: 'phaseOrder', dataType: 'uint8', access: 'ro' },
  { id: 0x301e, name: 'iqt', dataType: 'float', access: 'ro' },
  { id: 0x301f, name: 'boardTemp', dataType: 'int16', access: 'ro' },
  { id: 0x3020, name: 'iq', dataType: 'float', access: 'ro' },
  { id: 0x3021, name: 'id', dataType: 'float', access: 'ro' },
  { id: 0x3022, name: 'faultSta', dataType: 'uint32', access: 'ro' },
  { id: 0x3023, name: 'warnSta', dataType: 'uint32', access: 'ro' },
  { id: 0x3024, name: 'drv_fault', dataType: 'uint16', access: 'ro' },
  { id: 0x3025, name: 'drv_temp', dataType: 'float', access: 'ro' },
  { id: 0x3026, name: 'Uq', dataType: 'float', access: 'ro' },
  { id: 0x3027, name: 'Ud', dataType: 'float', access: 'ro' },
  { id: 0x3028, name: 'dtc_u', dataType: 'float', access: 'ro' },
  { id: 0x3029, name: 'dtc_v', dataType: 'float', access: 'ro' },
  { id: 0x302a, name: 'dtc_w', dataType: 'float', access: 'ro' },
  { id: 0x302b, name: 'v_bus', dataType: 'float', access: 'ro' },
  { id: 0x302c, name: 'torque_fdb', dataType: 'float', access: 'ro' },
  { id: 0x302d, name: 'rated_i', dataType: 'float', access: 'ro' },
  { id: 0x302e, name: 'limit_i', dataType: 'float', access: 'ro' },
  { id: 0x302f, name: 'spd_ref', dataType: 'float', access: 'ro' },
  { id: 0x3030, name: 'spd_reff', dataType: 'float', access: 'ro' },
  { id: 0x3031, name: 'zero_fault', dataType: 'uint8', access: 'ro' },
  { id: 0x3032, name: 'chasu_coder_raw', dataType: 'int16', access: 'ro' },
  { id: 0x3033, name: 'chasu_angle', dataType: 'float', access: 'ro' },
  { id: 0x3034, name: 'as_angle', dataType: 'float', access: 'ro' },
  { id: 0x3035, name: 'vel_max', dataType: 'float', access: 'ro' },
  { id: 0x3036, name: 'judge', dataType: 'uint8', access: 'ro' },
  { id: 0x3037, name: 'fault1', dataType: 'uint32', access: 'ro' },
  { id: 0x3038, name: 'fault2', dataType: 'uint32', access: 'ro' },
  { id: 0x3039, name: 'fault3', dataType: 'uint32', access: 'ro' },
  { id: 0x303a, name: 'fault4', dataType: 'uint32', access: 'ro' },
  { id: 0x303b, name: 'fault5', dataType: 'uint32', access: 'ro' },
  { id: 0x303c, name: 'fault6', dataType: 'uint32', access: 'ro' },
  { id: 0x303d, name: 'fault7', dataType: 'uint32', access: 'ro' },
  { id: 0x303e, name: 'fault8', dataType: 'uint32', access: 'ro' },
  { id: 0x303f, name: 'ElecOffset', dataType: 'float', access: 'ro' },
  { id: 0x3040, name: 'mcOverTemp', dataType: 'int16', access: 'ro' },
  { id: 0x3041, name: 'Kt_Nm/Amp', dataType: 'float', access: 'ro' },
  { id: 0x3042, name: 'Tqcall_Type', dataType: 'uint8', access: 'ro' },
  { id: 0x3043, name: 'low_position', dataType: 'float', access: 'ro' },
  { id: 0x3044, name: 'H', dataType: 'uint8', access: 'ro' },
].sort((a, b) => a.id - b.id);

export const ROBSTRIDE_ACCESS_LABELS = {
  rw: 'Read/Write',
  ro: 'Read-Only',
  config: 'Config',
  setting: 'Setting',
};

export function toRobstrideCliType(dataType) {
  const t = String(dataType || '').toLowerCase();
  if (t === 'uint8') return 'u8';
  if (t === 'uint16') return 'u16';
  if (t === 'uint32') return 'u32';
  if (t === 'int8') return 'i8';
  if (t === 'int16') return 'u16';
  if (t === 'int32') return 'u32';
  if (t === 'float') return 'f32';
  return '';
}

export function canRobstrideWrite(access) {
  return access === 'rw' || access === 'config' || access === 'setting';
}
